version: '3.7'
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
    depends_on:
      - ubuntu
      
  ubuntu:
    image: ubuntu
