version: '3.7'
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    secrets:
      - source: main
        target: /usr/share/nginx/html/index.html

secrets:
  main:
    file: ./index.html
