version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    healthcheck:
      test: curl -f http://localhost/ || exit 1
      interval: 5s
      timeout: 1s
      retries: 2
      start_period: 10s
